export const ImagePath = {
  red_pin: require('../assets/icons/Pin.png'),
  blue_pin: require('../assets/icons/Pin_1.png'),
  no_bookings: require('../assets/icons/using/no_bookings.png'),
  pin: require('../assets/icons/using/Pin.png'),
  next: require('../assets/icons/using/Next.png'),
  check: require('../assets/icons/check.png'),
  uncheck: require('../assets/icons/uncheck.png'),
  add_circle: require('../assets/icons/using/Add.png'),
  camera: require('../assets/icons/Camera.png'),
  searching_driver: require('../assets/icons/using/ride.png'),
  car: require('../assets/icons/using/car.png'),
  down_arrow: require('../assets/icons/using/down.png'),
  Up_arrow: require('../assets/icons/using/Uparrow.png'),
  accepted: require('../assets/icons/accepted.png'),
  rejected: require('../assets/icons/rejected.png'),
  offer: require('../assets/icons/offer.png'),
  message: require('../assets/icons/message.png'),
  taxi_logo: require('../assets/icons/taxi_logo.png'),
};
